name: Lingo.dev i18n

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  i18n-web:
    name: Run i18n for web (UI strings)
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: lingodotdev/lingo.dev@48f8b3bdf736ac8d792b252fa25de97058f14219 # main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          api-key: ${{ secrets.LINGODOTDEV_API_KEY }}
          pull-request: true
          pull-request-title: "i18n: Lingo (web)"
          commit-message: "i18n: Lingo Translation Update (web)"
          working-directory: "apps/web"
          parallel: true

  i18n-docs:
    name: Run i18n for docs (content)
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: lingodotdev/lingo.dev@48f8b3bdf736ac8d792b252fa25de97058f14219 # main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          api-key: ${{ secrets.LINGODOTDEV_API_KEY }}
          pull-request: true
          pull-request-title: "i18n: Lingo (docs)"
          commit-message: "i18n: Lingo Translation Update (docs)"
          working-directory: "apps/docs"
          parallel: true

  i18n-accelerate:
    name: Run i18n for accelerate (UI strings)
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: lingodotdev/lingo.dev@48f8b3bdf736ac8d792b252fa25de97058f14219 # main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          api-key: ${{ secrets.LINGODOTDEV_API_KEY }}
          pull-request: true
          pull-request-title: "i18n: Lingo (accelerate)"
          commit-message: "i18n: Lingo Translation Update (accelerate)"
          working-directory: "apps/accelerate"
          parallel: true
